### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shipanmiah** [Sam-Richard-007/Hamster-Kombat-Key-Generator#13]
this script automatic redirect to your TG channel

**Comment by Sam-Richard-007** [comment]
when ?? its working fine for me

**Comment by jebuskhoury** [comment]
Yeah it redirects to a TG Channel for selling Instagram followers

and the script.js is now obfuscated...

**Comment by Sam-Richard-007** [comment]
Yes It the Channel of the Creator of this Tool !

Is any issue in that ?

**Comment by jebuskhoury** [comment]
Not at all my friend, just pointing out that when you open the index.html with live server you cannot use the tool, it just redirects automatically to the tg channel

**Comment by Sam-Richard-007** [comment]
yes , because i noticed many people took my code without any Credits they are simply Modifying and using my code , that why i implemented this.

**Comment by jebuskhoury** [comment]
Thanks for your work :) good job.
