### ISSUE TITLE
Button for generate 1 "complect" of all keys )

### ISSUE THREAD

**Issue by HarmoniousInfinity** [Sam-Richard-007/Hamster-Kombat-Key-Generator#2]
Hello!
Can you add one button for generate 16 keys = 4x4 games, please )
It will be totally better and optimal then one by one. For personal use ofc once a day )
And only if one or some keys will be failed can use aditional at current state of realisation.

**Comment by Sam-Richard-007** [comment]
Yes it can be done , But It Increases the chances of making the Key Generation Failures

**Comment by DragAditya** [comment]
He Have Good Idea, what if We Do 1 key for each game

**Comment by Sam-Richard-007** [comment]
> He Have Good Idea, what if We Do 1 key for each game

Yes But Anyways It makes you to Generate 4Keys x 4 times to complete one day .

I think this will be better. 

If you have any Other Feedback don't hesitate to Comment out
