### ISSUE TITLE
`appToken` and `promoId`.

### ISSUE THREAD

**Issue by Master811129** [Sam-Richard-007/Hamster-Kombat-Key-Generator#4]
https://github.com/Sam-Richard-007/Hamster-Kombat-Key-Generator/blob/af47a171e76eea58bb5999176cc075c2c0a4fddd/script.js#L5C1-L10C3

are these values unique for every device?

**Comment by Sam-Richard-007** [comment]
Maybe I am Not sure with it

**Comment by Master811129** [comment]
Hmm, That could be a problem. If these code are non-unique then so the redeem codes. There is a possibility that They track the codes and ban users who use this tool.

> Maybe I am Not sure with it

Are you the original developer?

**Comment by Sam-Richard-007** [comment]
If Hamster Kombat want to Track they have chances to track based on the app ID and promo ID

Its all on your Own Risk.

**Comment by Master811129** [comment]
> If Hamster Kombat want to Track they have chances to track based on the app ID and promo ID

How did you generate that promo ID?
