### ISSUE TITLE
New game in Hamster Kombat

### ISSUE THREAD

**Issue by zedis-lv** [Sam-Richard-007/Hamster-Kombat-Key-Generator#7]
Hello it's a new game in hamster kombat "Twerk Race"
Can you please make ganarator for this game also?

**Comment by Sam-Richard-007** [comment]
New Game Twerk Race Added

[Do Join Our Telegram channel for More Info](https://t.me/Insta_Buy_Follower)

**Comment by zedis-lv** [comment]
If it's correct That appToken equal promoId in Twerk Race 3D key generation ???

        6: {
    name: 'Twerk Race 3D',
    appToken: '61308365-9d16-4040-8bb0-2f4a4c69074c',
    promoId: '61308365-9d16-4040-8bb0-2f4a4c69074c'
        }
